### ISSUE TITLE
APIM PermissionDenied

### ISSUE THREAD

**Issue by jefffeng-ai** [Azure/azure-openai-benchmark#16]
PermissionDenied

when i do PTU benchmarking, the requests succeed for the first 2 secs, no failures, then i continuously got following error, did anyone see this problem before?: 
![image](https://github.com/Azure/azure-openai-benchmark/assets/152949032/86b0b288-0c12-4939-943c-bcc750eca0cb)

**Comment by technicianted** [comment]
From screenshot it looks like no requests actually succeeded. Check that you have the correct deployment name and you've set `OPENAI_API_KEY` environment variable correctly.

You could also try using `curl` directly to see if you got the correct setup. [You can follow this example](https://learn.microsoft.com/en-us/azure/ai-services/openai/chatgpt-quickstart?tabs=command-line%2Cpython&pivots=rest-api#rest-api).

**Comment by technicianted** [comment]
Closing this as irrelevant. Please reach out to Azure support for similar issues.
