### ISSUE TITLE
Hidden/silent effects of MAX_RETRY_SECONDS

### ISSUE THREAD

**Issue by michaeltremeer** [Azure/azure-openai-benchmark#20]
hey there,

Correct me if I’m wrong, but within `aoairequester.py`, `MAX_RETRY_SECONDS` looks like it would have a big impact on the latency metrics once you reach a point where requests are being throttled and receiving 429s. If a request is 429ed after 5 seconds or more, it may be recorded as failed/throttled, and a new request will take its place with an even newer start time. In the real-world, if a user is throttled in an application, it would make sense that their request would be resent until a response is received, so from a user experience perspective, we are probably more interesting in when the first response is actually received.

While some sort of default for `MAX_RETRY_SECONDS` is logical, wouldn’t having this set to only 5 seconds mean that any results from the tool are only valid when the server load is low enough that most requests that receive a 429 once would still receive their first token by the new response? It seems like once the load is sufficient that 429s are being sent, the wait time of some of the theottled requests won’t be counted in the latency stats I since they never finished (only in the throttled count).

A few questions from me:

* Is the logic above sound? Is it a realistic issue?
* Would increasing `MAX_RETRY_SECONDS` to a more longer default, or making it configurable make sense? I see there is an unused timeout variable in the OAIRequester - was this an idea that existed already?
* Should the README be updated to make it clear how the `throttled` stat works, and what it may mean for the other metrics?

Edit: Updated with a rewording. After looking more closely at the code and 429 responses from the OAI endpoints, I am not so sure now if the above is correct. Please let me know your thoughts!

**Comment by technicianted** [comment]
The latency incurred due to retrying after a 429 should be part of the `ttft` and total request duration stats. If today it isn't then it is a bug and we should track it in a separate issue.

I agree that 5 seconds is too short. It makes sense to make it at least 60s and configurable by user.

Yes the README should explain this.

**Comment by michaeltremeer** [comment]
Let's continue discussion on the PR
